---
language: python
python: "2.7"
services:
  - docker
before_install:
  # Pull container
  - 'sudo docker pull oraclelinux:7.2'
  # Customize container
  - 'sudo docker build --rm=true --file=tests/Dockerfile --tag=ol7-db2:latest tests'

script:
  # Prepare tests
  - echo localhost > inventory
  - container_id=$(mktemp)

    # Run container in detached state
  - 'sudo docker run --detach --volume="${PWD}":/etc/ansible/roles ol7-db2:latest "/sbin/init" > "${container_id}"'

  # Syntax under docker 
  - 'sudo docker exec --tty "$(cat ${container_id})" env ansible-playbook /etc/ansible/roles/examples/full_example.yml --syntax-check'
  
  # Syntax check
  - "ansible-playbook -i localhost, examples/full_example.yml --syntax-check"

  # Run role
  - "ansible-playbook -i localhost, examples/full_example.yml --connection=local --tags parse"
  # Idempotency check
  - >
    ansible-playbook -i localhost, examples/full_example.yml --connection=local --tags parse
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotency: PASS' && exit 0)
    || (echo 'Idempotency: FAIL' && exit 1)