---
  - hosts: all
    gather_facts: True
    vars_files: 
     - myvars.yml
    roles:
      - Stouts.limits
    vars:
        # Configurações de limites
      - limits_limits:
          - "* hard nofile 65536"
          - "* soft nofile 65536"
          - "* hard nproc 10000"
          - "* soft nproc 10000"
      - limits_path: /etc/security/limits.conf

    tasks:

      - name: Desabilitando o SELinux
        selinux: state=disabled
        tags: setup

      - name: Adicionando entrada ao /etc/hosts
        lineinfile:
          dest: /etc/hosts
          regexp: "^{{ ansible_default_ipv4.address }} {{ ansible_hostname }}$"
          line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}"
        tags: setup

      - name: Baixando a chave de ativação do DB2 10.5 no FTP da LB2
        get_url:
          url: ftp://transfer.lb2.com.br/downloads/connections/DB2_ESE_AUSI_QS_Activ_10.5.0.5.zip
          dest: /tmp/db2_key.zip
        tags: download

      - name: Baixando o DB2 10.5 no FTP da LB2
        get_url:
          url: ftp://transfer.lb2.com.br/downloads/connections/DB2_Svr_10.5.0.3_Linux_x86-64.tar.gz
          dest: /tmp/db2_10503.tar.gz
        tags: download

      - name: Instalando repositorio OL Public repo
        get_url: 
          url: http://public-yum.oracle.com/public-yum-ol6.repo 
          dest: /etc/yum.repos.d/public-yum-release.repo
        tags: setup

      - name: Instalando os pacotes do DB2
        yum: name={{item}} state=installed update_cache=yes disable_gpg_check=yes
        with_items: db2_packages
        tags: setup

      - name: Descompacta o DB2 Server 10.5.3
        unarchive:
          src: /tmp/db2_10503.tar.gz
          dest: /tmp/
          copy: no
          creates: /tmp/server
        tags: setup

      - name: Realizando o DB2 Pre Requisits Check
        command: /tmp/server/db2prereqcheck -i -s
        register: precheck
        failed_when: "'failed' in precheck.stderr"
        changed_when: False 
        tags: setup

      - name: Adicionando grupos do DB2
        group: name={{item}} state=present
        with_items:
          - db2iadm1
          - db2fsdm1
          - dasadm1
        tags: setup

      - name: Adicionando o usuario DB2INST1
        user: name=db2inst1 comment="DB2 Instance user" group=db2iadm1 uid=1004 home=/home/db2inst1
        tags: setup

      - name: Adicionando o usuario DB2SDFE1
        user: name=db2sdfe1 comment="DB2 Fence user" group=db2fsdm1 uid=1003 home=/home/db2sdfe1
        tags: setup

      - name: Adicionando o usuario DASUSR1
        user: name=dasusr1 comment="DB2 DAS user" group=dasadm1 uid=1002 home=/home/dasusr1
        tags: setup

      - name: Aceitando a licença IBM automaticamente
        replace: 
          dest: /tmp/server/db2/linuxamd64/samples/db2server.rsp
          regexp: '^LIC_AGREEMENT             = DECLINE' 
          replace: 'LIC_AGREEMENT             = ACCEPT'
        tags: install 

      - name: Instalando o DB2 10.5
        command: /tmp/server/db2setup -r /tmp/server/db2/linuxamd64/samples/db2server.rsp
        args: 
          creates: /opt/ibm/db2/V10.5
        tags: install

      - name: Validando a Instalação
        command: /opt/ibm/db2/V10.5/bin/db2val -o
        register: db2_val
        failed_when: "'DBI1335I' not in db2_val.stdout"
        changed_when: False
        tags: ['install', 'validate']