---
# As mentioned by IBM if you set password,uid,gid,group_name 
# If you provide at least user,password and group_name DB2 setup will create those users
# TODO: Use the new block feature since `when` clause is equal on all tasks
  
- name: Creating DB2 Fenced Groups
  group: name="{{item.fenced_group_name}}" state=present 
  #gid= "{{ item.user_options.fenced_gid | default('544') }}"
  with_items: db2_instances
- name: Creating DB2 Instance Groups
  group: name="{{item.group_name}}" state=present 
  #gid= "{{ item.user_options.gid | default('543') }}"
  with_items: db2_instances

- name: Creating DB2 Instance Users
  user:
    name: "{{item.name}}"
    group: "{{item.group_name}}"
    password: "{{ item.user_options.password | default('ldUMKEu7/QCAY')}}"
    home: "/home/{{item.name}}"
    uid: "{{ item.user_options.uid | default('5401') }}"
  with_items: db2_instances
  when: item.user_options.home_directory is not defined

- name: Creating DB2 Instance Users
  user:
    name: "{{item.name}}"
    group: "{{item.group_name}}"
    password: "{{ item.user_options.password | default('ldUMKEu7/QCAY')}}"
    home: "{{ item.user_options.home_directory }}"
    uid: "{{ item.user_options.uid | default('5401') }}"
  with_items: db2_instances
  when: item.user_options.home_directory is defined

#TODO: Find a better way to cope with home_directory default value

- name: Creating DB2 Fenced Users
  user:
    name: "{{item.fenced_username}}"
    group: "{{item.fenced_group_name}}"
    password: "{{ item.user_options.fenced_password | default('ldUMKEu7/QCAY')}}"
    home: "/home/{{item.name}}"
    uid: "{{ item.user_options.fenced_uid | default('5402') }}"
  with_items: db2_instances
  when: item.user_options.fenced_home_directory is not defined

- name: Creating DB2 Fenced Users
  user:
    name: "{{item.fenced_username}}"
    group: "{{item.fenced_group_name}}"
    password: "{{ item.user_options.fenced_password | default('ldUMKEu7/QCAY')}}"
    home: "{{ item.user_options.fenced_home_directory}}"
    uid: "{{ item.user_options.fenced_uid | default('5402') }}"
  with_items: db2_instances
  when: item.user_options.fenced_home_directory is defined