---
# As mentioned by IBM if you set password,uid,gid,group_name 
# If you provide at least user,password and group_name DB2 setup will create those users
# TODO: Use the new block feature since `when` clause is equal on all tasks

- name: Creating DB2 Fenced Groups
  group: name="{{db2_instances.fenced_group_name}}" state=present
  when: db2_instances.options is not defined or db2_instances.options.fenced_password is not defined

- name: Creating DB2 Instance Groups
  group: name="{{db2_instances.group_name}}" state=present
  when: db2_instances.options is not defined or db2_instances.options.password is not defined

- name: Creating DB2 Instance Users
  user:
    name: "{{db2_instances.name}}"
    group: "{{db2_instances.group_name}}"
    password: ldUMKEu7/QCAY
    home: "/home/{{db2_instances.name}}"
  when: db2_instances.options is not defined or db2_instances.options.password is not defined

- name: Creating DB2 Fenced Users
  user:
    name: "{{db2_instances.fenced_username}}"
    group: "{{db2_instances.fenced_group_name}}"
    password: ldUMKEu7/QCAY
    home: "/home/{{db2_instances.fenced_username}}"
  when: db2_instances.options is not defined or db2_instances.options.fenced_password is not defined