---
  - include: get_db2.yml
    tags: download

  - include: instance_users.yml
    tags: ['users', 'setup']

  - name: Disabling SELinux
    selinux: state=disabled
    tags: setup

  - name: Adding entry to /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: "^{{ ansible_default_ipv4.address }} {{ ansible_hostname }}$"
      line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}"
    tags: setup

  - name: Installing DB2 pre requisites packages
    yum: name={{item}} state=installed update_cache={{make_cache}} disable_gpg_check=yes
    with_items: db2_packages
    tags: ['packages', 'setup']

  - name: Running DB2 Pre Requisits Check
    command: "{{db2_binary.dest}}/server/db2prereqcheck -i -s"
    register: precheck
    failed_when: "'failed' in precheck.stderr"
    changed_when: False 
    tags: setup

  - name: Parse response file
    template: src=db2server.j2.rsp dest=/tmp/db2server.rsp
    tags: parse

  - name: Installing DB2 10.5
    command: "{{db2_binary.dest}}/server/db2setup -r /tmp/db2server.rsp"
    args: 
      creates: "{{resp.file}}"
    tags: install

  - name: Validating the current installation
    command: "{{resp.file}}/bin/db2val -o"
    register: db2_val
    failed_when: "'DBI1335I' not in db2_val.stdout"
    changed_when: False
    tags: ['install', 'validate']